homeassistant:
  # Name of the location where Home Assistant is running
  name: Saurus Towers
  # Location required to calculate the time the sun rises and sets
  latitude: 52.18
  longitude: -2.22
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  base_url: saurustowers.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

zone: !include zones.yaml

# hass.io
hassio:

# Text to speech
tts:
  - platform: google

ifttt:
  key: bp7UAN4DkEmQYfv8kjE9-O

# Ikea Tradfri
tradfri:
  host: 192.168.1.94

# OctoPrint
#octoprint:
#  host: 192.168.1.103
#  api_key: !secret octoprint_api_key

# Media players
media_player:
  - platform: sonos
  - platform: cast
  - platform: roku

mqtt:
  broker: 192.168.1.118
  port: 1883
  username: homeassistant
  password: 7gggPbzt
  discovery: True

device_tracker:
  - platform: owntracks

notify:
  - platform: html5
    gcm_api_key: !secret gcm_api_key 
    gcm_sender_id: !secret gcm_sender_id

calendar:
  - platform: todoist
    token: !secret todoist_api_token

switch: !include switches.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
