homeassistant:
  # Name of the location where Home Assistant is running
  name: Saurus Towers
  # Location required to calculate the time the sun rises and sets
  latitude: 52.18
  longitude: -2.22
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

zone: !include zones.yaml

# hass.io
hassio:

# Text to speech
tts:
  - platform: google

alexa:

python_script:

ifttt:
  key: !secret ifttt_key

influxdb:
  host: 127.0.0.1

# Ikea Tradfri
tradfri:
  host: 192.168.1.94

## OctoPrint
#octoprint:
#  host: 192.168.1.103
#  api_key: !secret octoprint_api_key
#  bed: true
#  number_of_tools: 1

lametric:
  client_id: !secret lametric_client_id
  client_secret: !secret lametric_client_secret

# Media players
media_player:
  - platform: sonos
  - platform: cast
  - platform: roku

mqtt:
  broker: 192.168.1.118
  port: 1883

mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true

notify:
  - platform: html5
    gcm_api_key: !secret gcm_api_key 
    gcm_sender_id: !secret gcm_sender_id
  - name: lametric
    platform: lametric
    lifetime: 20
    icon: i96
    cycles: 3

camera:
  - platform: mjpeg
    name: Plantcam
    still_image_url: http://192.168.1.97/picture/1/current/
    mjpeg_url: http://192.168.1.97:8081

plant: !include plant.yaml
intent_script: !include_dir_named intents
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
panel_iframe: !include panel_iframes.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
