- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - feelslike_c
    - precip_today_metric
    - temp_c
    - temp_high_1d_c
    - temp_low_1d_c
    - weather_1d_metric

- platform: google_travel_time
  name: Home To Foxsoft
  api_key: !secret google_api_key
  origin: zone.home
  destination: zone.foxsoft
- platform: google_travel_time
  name: Home To Worcestershire County Council
  api_key: !secret google_api_key
  origin: zone.home
  destination: zone.worcestershire_county_council
