- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - feelslike_c
    - precip_today_metric
    - temp_c
    - temp_high_1d_c
    - temp_low_1d_c
    - weather_1d_metric

- platform: miflora
  mac: 'C4:7C:8D:65:58:2E'
  name: miflora_58_2e
  force_update: true
  timeout: 60
  cache_value: 60*60
  median: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  mac: 'C4:7C:8D:65:5B:7D'
  name: miflora_5b_7d
  force_update: true
  timeout: 60
  cache_value: 60*60
  median: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  mac: 'C4:7C:8D:65:60:C0'
  name: miflora_60_c0
  force_update: true
  timeout: 60
  cache_value: 60*60
  median: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  mac: 'C4:7C:8D:65:63:B8'
  name: miflora_63_b8
  force_update: true
  timeout: 60
  cache_value: 60*60
  median: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: google_travel_time
  name: Home To Foxsoft
  api_key: !secret google_api_key
  origin: zone.home
  destination: zone.foxsoft
- platform: google_travel_time
  name: Home To Worcestershire County Council
  api_key: !secret google_api_key
  origin: zone.home
  destination: zone.worcestershire_county_council
